### ISSUE TITLE
Phase 2 Stock ROM erzeugt Brick

### ISSUE THREAD

**Issue by SvenSFS** [oszilloskop/UBNT_ERX_Gluon_Factory-Image#1]
Hallo,
hab versucht die Anleitung umzusetzen nur leider Produziert die in Phase2 
von Lede auf Stock Rom einen Gebrickten Edge Router X SFP.

Beim Booten zur Phase 3 findet er das Root System nicht.

`Creating 7 MTD partitions on "MT7621-NAND":
0x000000000000-0x00000ff80000 : "ALL"
0x000000000000-0x000000080000 : "Bootloader"
0x000000080000-0x0000000e0000 : "Config"
0x0000000e0000-0x000000140000 : "eeprom"
0x000000140000-0x000000440000 : "Kernel"
0x000000440000-0x000000740000 : "Kernel2"
0x000000740000-0x00000ff00000 : "RootFS"
[mtk_nand] probe successfully!
UBNT BD mac f09fc2611c20 kidx 1 mrev 12 serial F09FC2611C20 type e51
rdm_major = 253
GMAC1_MAC_ADRH -- : 0x0000f09f
GMAC1_MAC_ADRL -- : 0xc2611c20
Ralink APSoC Ethernet Driver Initilization. v3.1  512 rx/tx descriptors allocated, mtu = 1500!
GMAC1_MAC_ADRH -- : 0x0000f09f
GMAC1_MAC_ADRL -- : 0xc2611c20
PROC INIT OK!
Ralink I2C Init
TCP: cubic registered
Initializing XFRM netlink socket
NET: Registered protocol family 17
NET: Registered protocol family 15
UBI: attaching mtd7 to ubi0
UBI error: scan_peb: bad image sequence number 653619244 in PEB 1892, expected 947180932
Erase counter header dump:
        magic          0x55424923
        version        1
        ec             4
        vid_hdr_offset 2048
        data_offset    4096
        image_seq      653619244
        hdr_crc        0xa92fddbb
erase counter header hexdump:
UBI error: ubi_attach_mtd_dev: failed to attach mtd7, error -22
UBI error: ubi_init: cannot attach mtd7
UBIFS error (pid 1): ubifs_mount: cannot open "ubi0_0", error -19
VFS: Cannot open root device "ubi0_0" or unknown-block(0,0): error -19
Please append a correct "root=" boot option; here are the available partitions:
1f00             512 mtdblock0  (driver?)
1f01          261632 mtdblock1  (driver?)
1f02             512 mtdblock2  (driver?)
1f03             384 mtdblock3  (driver?)
1f04             384 mtdblock4  (driver?)
1f05            3072 mtdblock5  (driver?)
1f06            3072 mtdblock6  (driver?)
1f07          253696 mtdblock7  (driver?)
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
kklö

`

Gruss
Sven

**Comment by oszilloskop** [comment]
Welche Version der Stockfirmware hast Du versucht aufzuspielen?

**Comment by SvenSFS** [comment]
v1.10.5, zudem auch mal die alte mit der er ausgeliefert wurde, 1.9.7-hotfix4 hat
aber nicht geholfen.

**Comment by oszilloskop** [comment]
Hm, ich habe das ganze mit der Stockfirmware `1.9.7-hotfix4` aufgesetzt und getestet.

Das ganze Prozedur habe ich von:
https://community.ubnt.com/t5/EdgeRouter/ERX-ERX-SFP-System-Recovery/td-p/2056921
abgeleitet. Dort wird direkt mit TFTP gearbeitet.
Bei dem von mir beschriebenem Verfahren wird lediglich Phase 1 anstelle von TFTP angewendet.


Ist dein Router denn jetzt total gebrickt, oder kannst Du noch per TFTP die Stockfirmware aufspielen?

**Comment by SvenSFS** [comment]
Nö LEDE bzw. unser Berliner Freifunk Image kann ich immer wieder drauf wuppen. 
Ich hab das alles per TFTP gemacht, dann muss ich nicht immer die Netzwerke Tauschen. 

Mit LEDE Rennt der Super, nur das der SFP Anschluss nicht Funktioniert, genau den brauch ich aber.

**Comment by oszilloskop** [comment]
Gibt es hier noch Informations- oder Klärungsbedarf bzw. gibt es hier noch weiter Informationen zu dem Problem?

**Comment by SirToffski** [comment]
Hi, a quick question about reverting back to stock image. I've read the process which seems to be straightforward, but just to confirm - is there a step in the process which requires using TFTP with TLL Serial cable?

From what I understood reverting to stock can be achieved with only using a LAN port + SSH, is this correct?

Thank you!

**Comment by oszilloskop** [comment]
You are right. 
All you need is one of my  back-to-stock initramfs-kernel.bin image and SSH connections (Phase 1 and Phase 2). TFTP is not necessary. That means also no TLL Serial cable.
That's why I published this procedure.

**Comment by SirToffski** [comment]
Thanks! Will try it out later this evening. Any specific stock firmware version you'd recommend for the initial flash? I've downloaded `1.9.7-hotfix4` as mentioned in previous comments, thought I think my ERX came with `1.10.7`.

**Comment by oszilloskop** [comment]
I only did it with 1.9.7-hotfix4

**Comment by SirToffski** [comment]
I've just tried it with 1.9.7-hotfix4. Unfortunately the ERX is now bricked.. Everything went well until the final reboot at step 2. Hard reset, attempts to put the thing in recovery mode, etc didnt work.

I pulled out Wireshark and there are not packets/frames - anything coming out of the ERX. I kind of expected that might happen anyways. Will get the TTL cable and try the TFTP recovery next.

**Comment by oszilloskop** [comment]
If you were able to execute the command sequence of step 2 without warnings or errors and the device stopped responding after a following reboot, then something was wrong with your command sequence or with the 1.9.7-hotfix4 bin files.

Please let us know what you will find out by using the TTL cable.

**Comment by SirToffski** [comment]
Finally got the TTL cable and recovered the ERX yesterday evening. I’ve saved the boot logs , will share soon.

**Comment by SirToffski** [comment]
Here's what the boot log showed:
```
PROC INIT OK!
Ralink I2C Init
TCP: cubic registered
Initializing XFRM netlink socket
NET: Registered protocol family 17
NET: Registered protocol family 15
UBI: attaching mtd7 to ubi0
UBI error: scan_peb: bad image sequence number 651866360 in PEB 32, expected 115  2541750
Erase counter header dump:
        magic          0x55424923
        version        1
        ec             0
        vid_hdr_offset 2048
        data_offset    4096
        image_seq      651866360
        hdr_crc        0xd727df54
erase counter header hexdump:
UBI error: ubi_attach_mtd_dev: failed to attach mtd7, error -22
UBI error: ubi_init: cannot attach mtd7
UBIFS error (pid 1): ubifs_mount: cannot open "ubi0_0", error -19
VFS: Cannot open root device "ubi0_0" or unknown-block(0,0): error -19
Please append a correct "root=" boot option; here are the available partitions:
1f00             512 mtdblock0  (driver?)
1f01          261632 mtdblock1  (driver?)
1f02             512 mtdblock2  (driver?)
1f03             384 mtdblock3  (driver?)
1f04             384 mtdblock4  (driver?)
1f05            3072 mtdblock5  (driver?)
1f06            3072 mtdblock6  (driver?)
1f07          253696 mtdblock7  (driver?)
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
```

Also, reverting to stock is now super simple using the official Ubiquiti recovery image - [link](https://help.ubnt.com/hc/en-us/articles/360018189493-EdgeRouter-Manual-TFTP-Recovery).
All it takes is to choose `  1: Load system code to SDRAM via TFTP.` and select the image, not bad!

Btw after having stock firmware installed - I've gone back to OpenWTR pretty quickly, much less bloated and flexible.
