### ISSUE TITLE
Sysupgrade to Gluon 2020.2.2 based firmware fails

### ISSUE THREAD

**Issue by goligo** [oszilloskop/UBNT_ERX_Gluon_Factory-Image#2]
The latest FFMUC Firmware for ER-X is based on Gluon 2020.2 and fails to install via sysupgrade from the base image. As a workaround you need to install the old version based on 2020.1 first and then upgrade to the current version.

FFMUC current firmware: https://firmware.ffmuc.net/v2020.3.2/sysupgrade/gluon-ffmuc-v2020.3.2-ubnt-erx-sysupgrade.bin
FFMUC old firmware: https://firmware.ffmuc.net/v2020.2.4/sysupgrade/gluon-ffmuc-v2020.2.4-ubnt-erx-sysupgrade.bin

Is it possible to build a new set of factory images, based on Gluon 2020.2, to get rid of this issue?

**Comment by oszilloskop** [comment]
Was bedeutet "fails to install via sysupgrade"? Brick?
Ich werde mir das die Tage mal ansehen.

**Comment by goligo** [comment]
"fails" bedeutet hier, nach dem Sysupgrade und dem Neustart ist das Gerät nicht per HTTP ansprechbar. Ich nehme mal an, das meinst Du mit Brick.

**Comment by oszilloskop** [comment]
So, ich habe mich mal auf die serielle Konsole eines ERX verbunden.
Das Problem liegt nicht an den hier angebotenen Factory-Images. Es liegt irgendwie an der Münchner Firmware. (Die Punkte 3. und 4. zeigen dieses auf.)  

- Ist der Knoten bereits vorkonfiguriert, dann funktioniert ein Sysupgrade auf die neuere Münchner Firmware.
- Ist der Knoten noch nicht konfiguriert, dann hängt der Knoten nach einem Sysupgrade auf die neuere Münchner Firmware. (Das gleiche gilt für das Absetzen des `firstboot` Kommandos.)

tl;dr

1) Ich kann das beschrieben Problem mit der neueren Münchner Firmware nachstellen. Beim ersten Bootvorgang (nach dem initial Sysupgrade) hängt der unkonfigurierte Knoten nach/bei/während der ersten Zufallszahleninitialisierung/-behandlung.
Siehe Bootlog:  https://paste.tecff.de/?96e0880c1b68b98b#X0QHZ0vyHL0WfpLQJ1GlDcaQF97bjEF1VWBplN4j2Zk=

2) Bei dem Workaround über eine ältere Münchner Firmware funktioniert der Knoten offensichtlich erstmal wie von Dir angedeutet:

2a) Der erste Bootvorgang des uninitialisierten Knoten (nach dem initial Sysupgrade) mit der älteren Münchner Firmware sieht so aus: 
Siehe Bootlog: https://paste.tecff.de/?3e77d0145eb54fc2#ocz/D97iUrkE7DtxbqPoS0OHlj6vKU4kL6WRm0JNs3A=

2b) Der Bootvorgang nach der gefolgten Konfiguration über die Konfig-Seite sieht dann so aus:
Siehe Bootlog: https://paste.tecff.de/?4b26f62cfb8d1925#TkSi17cDXvH3CsDAuYpUP1XNoM6FXM2Xgc1hnGlLesg=

2c) Der erste Bootvorgang nach einem gefolgtem Sysupgrade (Konfigmodus mit Übernahme der Parameter) auf die neuere Münchner Firmware sieht dann so aus (läuft durch):
Siehe Bootlog: https://paste.tecff.de/?a28673d144253d3b#U9pcWfInZMsjGto6K/aZ8WN7CvkgR9oRrIJWf0RHY1Q=

3) Wird jetzt jedoch (nach 2c) ein `firstboot` auf dem Knoten abgesetzt dann bleibt der folgende Bootvorgang wieder hängen. **(Der Bootvorgang hängt an der gleichen Stelle wie bei 1.)**
Siehe Bootlog: https://paste.tecff.de/?1fe14a1f75f4bf8b#EqOQegFY+4t/PrgSYj2D9ea6BQXFiCbTEaMsXs3/sbo=  
Ich behaupte mal, dass Du deinen Knoten mit der neueren Münchner Firmware mit einem `firstboot` auch brickst.  
Daher hat das Verhalten nichts mit meinen Images hier zu tun.

4) **Ein Vergleichstest mit der aktuellen Frankfurter Firmware (unmodifiziertes Gluon v2020.2.2) zeigte keinerlei Auffälligkeiten.**
Siehe Bootlog:  https://paste.tecff.de/?6a56d33cdc80f9d9#s22oUxSQm8Rhe0S56FXQaJia1aZFuuZXAdXEWy8FlzY=

**Comment by goligo** [comment]
Vielen Dank fuer Deine ausfuehrliche Analyse!

**Comment by oszilloskop** [comment]
Halte mich bitte mal auf dem Laufenden.
Wenn es etwas ERX-spezifisches sein sollte, dann pack ich das hier mit in die Doku.

**Comment by goligo** [comment]
Kann es sein, dass es das gleiche Problem ist wie in https://github.com/freifunk-gluon/gluon/issues/1806 ? Da war es so, dass "wg genkey" hing, wegen fehlender Entropie?

**Comment by goligo** [comment]
Also ich bin ziemlich sicher, dass es genau das gleiche Problem ist, weil wir auch "wg genkey" in unserem upgrade-Script rufen. Was uns noch Rätsel aufgibt: Warum funktioniert das auf allen anderen Plattformen und nur auf dem ER-X nicht?

**Comment by oszilloskop** [comment]
Wireguard hatte ich jetzt garnicht auf dem Schirm. Klar, das wird in München jetzt ja eingesetzt.
