### ISSUE TITLE
Unreachable after gluon-ffmuc-v2020.3.2-ubnt-erx-sysupgrade

### ISSUE THREAD

**Issue by pkoerner81929** [oszilloskop/UBNT_ERX_Gluon_Factory-Image#3]
Installed generic Gluon2020.1-ubnt-erx-initramfs-factory.tar. Started sysupgrade for above versions. 
Now, router cannot reached anymore. No port, neither DHCP nor static IP.

Any idea before trying to restore via serial console?

Peter

**Comment by awlx** [comment]
Please use our newest firmware release!

https://firmware.ffmuc.net/v2020.3.2.1/sysupgrade/

**Comment by oszilloskop** [comment]
@pkoerner81929 
In diesem Falle wirst Du wohl nicht um die serielle Konsole herum kommen.
Schau dazu bitte in das bereits geschlossene Issue #2 . Dort ist beschrieben, warum es zu einem Soft-Brick kommt.

**Comment by awlx** [comment]
Oder vielleicht nen Tag stehen lassen bis er genug Zufallszahlen hat :x.

**Comment by pkoerner81929** [comment]
Ok, will let him think about it for a day ;-)

**Comment by awlx** [comment]
I suggest we close this issue as it's solved with the newest firmware.
